# Generated by Django 3.2.11 on 2022-01-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cpf',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_documento',
            field=models.CharField(default='CPF', max_length=3),
        ),
    ]
