# Generated by Django 2.2.9 on 2021-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='device_limit_creation',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='devices_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
