# Generated by Django 2.2.9 on 2021-09-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('Gratuito', 'Gratuito'), ('Pago_pessoal', 'Pago_pessoal'), ('Pago_empresarial', 'Pago_empresarial')], default='Gratuito', max_length=255)),
                ('limite_redes_iot', models.IntegerField(default=1)),
                ('limite_dispositivos_iot', models.IntegerField(default=5)),
                ('limite_requisicoes', models.IntegerField(default=100)),
                ('periodo', models.IntegerField(default=1)),
                ('unidade_tempo', models.CharField(choices=[('mes(es)', 'mes(es)'), ('ano(s)', 'ano(s)')], default='mes(es)', max_length=255)),
                ('ativo', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['id'],
            },
        ),
    ]
