# Generated by Django 3.2.11 on 2022-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220119_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_documento',
            field=models.ImageField(blank=True, upload_to='fotos_documentos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG')], default='CPF', max_length=3),
        ),
    ]
