# Generated by Django 3.2.7 on 2021-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='network_limit_creation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
