# Generated by Django 3.2.11 on 2022-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220125_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_documento',
            field=models.ImageField(blank=True, upload_to='fotosDocumentos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='fotosPerfil'),
        ),
    ]
