# Generated by Django 3.2.7 on 2022-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_network_limit_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='networks_created',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
