# Generated by Django 2.2.9 on 2021-09-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210903_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='plano',
            field=models.CharField(choices=[('Pago_pessoal', 'Pago_pessoal'), ('Pago_empresarial', 'Pago_empresarial')], default='Gratuito', max_length=255),
        ),
    ]
