# Generated by Django 2.2.9 on 2021-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210903_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='plano',
            field=models.CharField(choices=[('Pessoal', 'Pessoal'), ('Empresarial', 'Empresarial')], default='Pessoal', max_length=255),
        ),
    ]
