# Generated by Django 2.2.9 on 2021-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210903_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.CharField(choices=[('Trimestral', '3_meses'), ('Semestral', '6_meses'), ('anual', '1_ano')], default='Trimestral', max_length=255),
        ),
    ]
