# Generated by Django 2.2.9 on 2021-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210903_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='limite_dispositivos_iot',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plano',
            name='limite_redes_iot',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='plano',
            name='periodo',
            field=models.CharField(choices=[('Trimestral', '3 meses'), ('Semestral', '6 meses'), ('anual', '1 ano')], default='Trimestral', max_length=255),
        ),
    ]
