# Generated by Django 3.2.7 on 2022-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_rede_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='nome_rede',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
