# Generated by Django 3.2.7 on 2022-01-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_rede_nome_rede'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=255)),
                ('serial', models.SlugField(max_length=255, unique=True)),
                ('placa', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Atuador', 'atuador'), ('Sensor', 'sensor')], max_length=255)),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.rede')),
            ],
            options={
                'verbose_name': 'Dispositivo-Rede',
                'verbose_name_plural': 'Dispositivos-Rede',
                'ordering': ['id'],
            },
        ),
    ]
