# Generated by Django 3.2.7 on 2021-10-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('pino', models.IntegerField()),
                ('sinal', models.CharField(choices=[('Ligado', 'True'), ('Desligado', 'False')], max_length=255)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='devicesapi.dispositivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
