# Generated by Django 2.2.9 on 2021-08-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='usuario',
        ),
    ]
