# Generated by Django 3.2.7 on 2021-10-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0002_acoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acoes',
            options={'ordering': ['id'], 'verbose_name': 'Acao', 'verbose_name_plural': 'Acoes'},
        ),
        migrations.AlterModelOptions(
            name='configuracoes',
            options={'ordering': ['id'], 'verbose_name': 'Configuracao', 'verbose_name_plural': 'Configuracoes'},
        ),
        migrations.AlterField(
            model_name='acoes',
            name='pino',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='sinal',
            field=models.CharField(choices=[('Ligado', 'True'), ('Desligado', 'False')], default='True', max_length=255),
        ),
    ]
