# Generated by Django 2.2.9 on 2021-08-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0002_remove_dados_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='devicesapi.Dispositivo'),
        ),
    ]
