# Generated by Django 2.2.9 on 2021-08-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0003_auto_20210826_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='devicesapi.Dispositivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
