# Generated by Django 3.2.7 on 2021-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0003_auto_20211012_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='grupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
