# Generated by Django 3.2.7 on 2022-01-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_remove_rede_dispositivos'),
        ('devicesapi', '0004_dispositivo_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.rede'),
        ),
    ]
