# Generated by Django 2.2.9 on 2021-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0004_configuracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='limite_inferior',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='limite_superior',
            field=models.CharField(max_length=255),
        ),
    ]
