# Generated by Django 3.2.7 on 2022-01-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0005_dispositivo_rede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='rede',
        ),
    ]
