# Generated by Django 2.2.9 on 2021-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesapi', '0005_auto_20210830_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='limite_inferior',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='limite_superior',
            field=models.CharField(default='100', max_length=255),
        ),
    ]
