# Generated by Django 3.2.7 on 2022-01-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_dispositivorede'),
        ('devicesapi', '0006_auto_20220106_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='dispositivo_rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes_dispositivo_rede', to='networks.dispositivorede'),
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='dispositivo_rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_dispositivo_rede', to='networks.dispositivorede'),
        ),
        migrations.AddField(
            model_name='dados',
            name='dispositivo_rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados_dispositivo_rede', to='networks.dispositivorede'),
        ),
        migrations.AddField(
            model_name='mensagens',
            name='dispositivo_rede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_dispositivo_rede', to='networks.dispositivorede'),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='devicesapi.dispositivo'),
        ),
        migrations.AlterField(
            model_name='configuracoes',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='devicesapi.dispositivo'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='devicesapi.dispositivo'),
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='devicesapi.dispositivo'),
        ),
    ]
